[package]
name = "status_bar"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.30"
wayland-protocols = { version = "0.30", features = ["client"] }
wayland-protocols-wlr = { version = "0.1", features = ["client"] }